coverage:
  range: "30...80"
  notify:
    gitter:
      default:
        branches:
        - master
        threshold: 0
        url: https://webhooks.gitter.im/e/0334e6f55c6dfb45637c
  status:
    project: yes
    patch: no
    changes: no

comment:
  layout: "header, diff, trends, sunburst, uncovered"
