comment:
  layout: "header, diff, trends, uncovered"
  range: "30...80"

coverage:
  notify:
    gitter:
      default:
        branches:
        - master
        threshold: 0
        url: https://webhooks.gitter.im/e/0334e6f55c6dfb45637c

status:
  project: yes
  patch: no
  changes: no
