# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/pip

before_cache:
  - find "$HOME/.sbt" -name "*.lock" -print -delete
  - find "$HOME/.ivy2" -name "ivydata-*.properties" -print -delete

language: scala
script: project/bin/run-travis
jdk:
  - oraclejdk8

scala: 2.11.7

# codecov
before_install: pip install --user codecov
after_success: codecov
