# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers/0.13.8

language: scala
script: bin/run-travis
jdk:
  - oraclejdk7
  - oraclejdk8

scala: latest # set a dummy value as this build configuration does not rely on TRAVIS_SCALA_VERSION

# codecov
before_install: pip install --user codecov
after_success: codecov
