# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala
script: bin/run-travis
jdk:
  - oraclejdk7
  - oraclejdk8
scala:
  - 2.11.4
