# Use Docker-based container (instead of OpenVZ)
sudo: false
language: scala
scala:
- 2.11.8
- 2.12.0-M4
jdk: oraclejdk8
script: ./.ci/run.sh

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.coursier
  - $HOME/.sbt

before_cache:
- find "$HOME/.sbt" -name "*.lock" -print -delete
- find "$HOME/.ivy2" -name "ivydata-*.properties" -print -delete

# codecov
before_install: pip install --user codecov
after_success: codecov

env:
  global:
  - COURSIER_NO_TERM=1
