coverage:
  ignore:
    - "testing/*"

  status:
    changes:                   # if there are any unexpected changes in coverage
      enabled: false           # must be yes|true to enable this status

comment:
  layout: header, diff, changes, sunburst, uncovered
