comment:
  layout: header, changes, diff
coverage:
  ignore:
  - std/src/main/scala/Vec.scala
  - std/src/main/scala/vecutil.scala
  - project/testOnly
  notify:
    gitter:
      default:
        branches:
        - master
        threshold: 0
        url: https://webhooks.gitter.im/e/0334e6f55c6dfb45637c
  
